[tool.poetry]
name = "santander-cod3rs"
version = "0.1.0"
description = ""
authors = ["macedocoding <macedo@tuta.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10.13"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
